- name: add ssh key for jamie
  authorized_key:
    user: jamie
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZQgnyRpzP8vP/ZJq1PU3HnT4FPTiQWSrQNun6u7rir Real Ansible"

- name: generate sshd_config file from template
  tags: ssh
  template: 
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd